### PR TITLE
rk3588: enable wireguard in kernel

### PR DESCRIPTION
**Pull request by kanchev1**
Enable the wireguard module in the linux-rockchip-rk3588-5.10.110 package.

I've also provided prebuilt binaries which I've tested on my Rock PI 5B:
see https://github.com/BredOS/bred-repo/pull/3

### CODE REVIEW

**Review by Rippanda12 — APPROVED** [review]

**Comment by Rippanda12** [comment]
I will test this when I get home
(Unrelated but @kanchev1 are you Bulgarian?)

**Comment by bill88t** [comment]
Turns out the r58x I got has the `linux-rockchip` kernel, which has wireguard already in and enabled.

Reassigned to the bred man.

**Comment by kanchev1** [comment]
@Rippanda12 yes, zdravei! :-)

@bill88t what kind of board do you have, how is this possible?

Btw since I've created the pull requests I've been using the kernel without any issues on my Rock Pi 5B

**Comment by Rippanda12** [comment]
He has an r58X but he's using it as a server so he can't restart it ive tested it on my r5b but idk if it works since I don't know how to use it (unrelated but @kanchev1 wanna chat somewhere else I got discord and tg my handle is the same as gh)

**Comment by bill88t** [comment]
So long as `modprobe wireguard` works, with this change it should be good to go.

**Comment by bill88t** [comment]
I can't test, because I use the `linux-rockchip` kernel instead of the `linux-rockchip-rk3588` kernel, because that's what has my board's dtbs. Even though both boards have rk3588 we are using different kernels.

If it was just a few restarts I wouldn't mind.

**Pull request merged**
